spring.application.name=lab-resource-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_Resource_Utilization_Platform
spring.datasource.username=postgres
spring.datasource.password=rabin0437v
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT config - in production, move jwt.secret to an environment variable, not source control
jwt.secret=3dde8b4a88e21bf6d1a19c14ae44373df8ca33a432ffcfb2d8f62aed33e62832
jwt.expiration-ms=86400000