package com.lrplatform.model.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,
    MAINTENANCE_SCHEDULED,
    MAINTENANCE_COMPLETED,
    CALIBRATION_DUE,
    EQUIPMENT_AVAILABLE,
    WAITLIST_PROMOTED,
    PARTNERSHIP_INVITATION,
    ANNOUNCEMENT,
    PASSWORD_RESET,
    IDLE_EQUIPMENT_ALERT,
    GENERAL
}
