/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppDemandRouteImport } from './routes/_app.demand'
import { Route as AppEquipmentRouteImport } from './routes/_app.equipment'
import { Route as AppHeatmapsRouteImport } from './routes/_app.heatmaps'
import { Route as AppOptimizationRouteImport } from './routes/_app.optimization'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppResourceSharingRouteImport } from './routes/_app.resource-sharing'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppUtilizationRouteImport } from './routes/_app.utilization'
import { Route as AppWaitlistRouteImport } from './routes/_app.waitlist'
import { Route as AppDepartmentHeadDashboardRouteImport } from './routes/_app.department-head.dashboard'
import { Route as AppInstitutionAdminDashboardRouteImport } from './routes/_app.institution-admin.dashboard'
import { Route as AppManagerDashboardRouteImport } from './routes/_app.manager.dashboard'
import { Route as AppResearcherDashboardRouteImport } from './routes/_app.researcher.dashboard'
import { Route as AppStudentDashboardRouteImport } from './routes/_app.student.dashboard'
import { Route as AppSystemAdminDashboardRouteImport } from './routes/_app.system-admin.dashboard'
import { Route as AppTechnicianDashboardRouteImport } from './routes/_app.technician.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandRoute = AppDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapsRoute = AppHeatmapsRouteImport.update({
  id: '/heatmaps',
  path: '/heatmaps',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationRoute = AppOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResourceSharingRoute = AppResourceSharingRouteImport.update({
  id: '/resource-sharing',
  path: '/resource-sharing',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppUtilizationRoute = AppUtilizationRouteImport.update({
  id: '/utilization',
  path: '/utilization',
  getParentRoute: () => AppRoute,
} as any)
const AppWaitlistRoute = AppWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentHeadDashboardRoute =
  AppDepartmentHeadDashboardRouteImport.update({
    id: '/department-head/dashboard',
    path: '/department-head/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppInstitutionAdminDashboardRoute =
  AppInstitutionAdminDashboardRouteImport.update({
    id: '/institution-admin/dashboard',
    path: '/institution-admin/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppManagerDashboardRoute = AppManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppResearcherDashboardRoute = AppResearcherDashboardRouteImport.update({
  id: '/researcher/dashboard',
  path: '/researcher/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentDashboardRoute = AppStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemAdminDashboardRoute = AppSystemAdminDashboardRouteImport.update({
  id: '/system-admin/dashboard',
  path: '/system-admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTechnicianDashboardRoute = AppTechnicianDashboardRouteImport.update({
  id: '/technician/dashboard',
  path: '/technician/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/bookings': typeof AppBookingsRoute
  '/demand': typeof AppDemandRoute
  '/equipment': typeof AppEquipmentRoute
  '/heatmaps': typeof AppHeatmapsRoute
  '/optimization': typeof AppOptimizationRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/resource-sharing': typeof AppResourceSharingRoute
  '/users': typeof AppUsersRoute
  '/utilization': typeof AppUtilizationRoute
  '/waitlist': typeof AppWaitlistRoute
  '/department-head/dashboard': typeof AppDepartmentHeadDashboardRoute
  '/institution-admin/dashboard': typeof AppInstitutionAdminDashboardRoute
  '/manager/dashboard': typeof AppManagerDashboardRoute
  '/researcher/dashboard': typeof AppResearcherDashboardRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
  '/system-admin/dashboard': typeof AppSystemAdminDashboardRoute
  '/technician/dashboard': typeof AppTechnicianDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/bookings': typeof AppBookingsRoute
  '/demand': typeof AppDemandRoute
  '/equipment': typeof AppEquipmentRoute
  '/heatmaps': typeof AppHeatmapsRoute
  '/optimization': typeof AppOptimizationRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/resource-sharing': typeof AppResourceSharingRoute
  '/users': typeof AppUsersRoute
  '/utilization': typeof AppUtilizationRoute
  '/waitlist': typeof AppWaitlistRoute
  '/department-head/dashboard': typeof AppDepartmentHeadDashboardRoute
  '/institution-admin/dashboard': typeof AppInstitutionAdminDashboardRoute
  '/manager/dashboard': typeof AppManagerDashboardRoute
  '/researcher/dashboard': typeof AppResearcherDashboardRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
  '/system-admin/dashboard': typeof AppSystemAdminDashboardRoute
  '/technician/dashboard': typeof AppTechnicianDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/demand': typeof AppDemandRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/heatmaps': typeof AppHeatmapsRoute
  '/_app/optimization': typeof AppOptimizationRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/resource-sharing': typeof AppResourceSharingRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/utilization': typeof AppUtilizationRoute
  '/_app/waitlist': typeof AppWaitlistRoute
  '/_app/department-head/dashboard': typeof AppDepartmentHeadDashboardRoute
  '/_app/institution-admin/dashboard': typeof AppInstitutionAdminDashboardRoute
  '/_app/manager/dashboard': typeof AppManagerDashboardRoute
  '/_app/researcher/dashboard': typeof AppResearcherDashboardRoute
  '/_app/student/dashboard': typeof AppStudentDashboardRoute
  '/_app/system-admin/dashboard': typeof AppSystemAdminDashboardRoute
  '/_app/technician/dashboard': typeof AppTechnicianDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/analytics'
    | '/bookings'
    | '/demand'
    | '/equipment'
    | '/heatmaps'
    | '/optimization'
    | '/profile'
    | '/reports'
    | '/resource-sharing'
    | '/users'
    | '/utilization'
    | '/waitlist'
    | '/department-head/dashboard'
    | '/institution-admin/dashboard'
    | '/manager/dashboard'
    | '/researcher/dashboard'
    | '/student/dashboard'
    | '/system-admin/dashboard'
    | '/technician/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/analytics'
    | '/bookings'
    | '/demand'
    | '/equipment'
    | '/heatmaps'
    | '/optimization'
    | '/profile'
    | '/reports'
    | '/resource-sharing'
    | '/users'
    | '/utilization'
    | '/waitlist'
    | '/department-head/dashboard'
    | '/institution-admin/dashboard'
    | '/manager/dashboard'
    | '/researcher/dashboard'
    | '/student/dashboard'
    | '/system-admin/dashboard'
    | '/technician/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/analytics'
    | '/_app/bookings'
    | '/_app/demand'
    | '/_app/equipment'
    | '/_app/heatmaps'
    | '/_app/optimization'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/resource-sharing'
    | '/_app/users'
    | '/_app/utilization'
    | '/_app/waitlist'
    | '/_app/department-head/dashboard'
    | '/_app/institution-admin/dashboard'
    | '/_app/manager/dashboard'
    | '/_app/researcher/dashboard'
    | '/_app/student/dashboard'
    | '/_app/system-admin/dashboard'
    | '/_app/technician/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demand': {
      id: '/_app/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof AppDemandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heatmaps': {
      id: '/_app/heatmaps'
      path: '/heatmaps'
      fullPath: '/heatmaps'
      preLoaderRoute: typeof AppHeatmapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/optimization': {
      id: '/_app/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof AppOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resource-sharing': {
      id: '/_app/resource-sharing'
      path: '/resource-sharing'
      fullPath: '/resource-sharing'
      preLoaderRoute: typeof AppResourceSharingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utilization': {
      id: '/_app/utilization'
      path: '/utilization'
      fullPath: '/utilization'
      preLoaderRoute: typeof AppUtilizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waitlist': {
      id: '/_app/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AppWaitlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/department-head/dashboard': {
      id: '/_app/department-head/dashboard'
      path: '/department-head/dashboard'
      fullPath: '/department-head/dashboard'
      preLoaderRoute: typeof AppDepartmentHeadDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institution-admin/dashboard': {
      id: '/_app/institution-admin/dashboard'
      path: '/institution-admin/dashboard'
      fullPath: '/institution-admin/dashboard'
      preLoaderRoute: typeof AppInstitutionAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/dashboard': {
      id: '/_app/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AppManagerDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/researcher/dashboard': {
      id: '/_app/researcher/dashboard'
      path: '/researcher/dashboard'
      fullPath: '/researcher/dashboard'
      preLoaderRoute: typeof AppResearcherDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/dashboard': {
      id: '/_app/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AppStudentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-admin/dashboard': {
      id: '/_app/system-admin/dashboard'
      path: '/system-admin/dashboard'
      fullPath: '/system-admin/dashboard'
      preLoaderRoute: typeof AppSystemAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/technician/dashboard': {
      id: '/_app/technician/dashboard'
      path: '/technician/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof AppTechnicianDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppDemandRoute: typeof AppDemandRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppHeatmapsRoute: typeof AppHeatmapsRoute
  AppOptimizationRoute: typeof AppOptimizationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResourceSharingRoute: typeof AppResourceSharingRoute
  AppUsersRoute: typeof AppUsersRoute
  AppUtilizationRoute: typeof AppUtilizationRoute
  AppWaitlistRoute: typeof AppWaitlistRoute
  AppDepartmentHeadDashboardRoute: typeof AppDepartmentHeadDashboardRoute
  AppInstitutionAdminDashboardRoute: typeof AppInstitutionAdminDashboardRoute
  AppManagerDashboardRoute: typeof AppManagerDashboardRoute
  AppResearcherDashboardRoute: typeof AppResearcherDashboardRoute
  AppStudentDashboardRoute: typeof AppStudentDashboardRoute
  AppSystemAdminDashboardRoute: typeof AppSystemAdminDashboardRoute
  AppTechnicianDashboardRoute: typeof AppTechnicianDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppDemandRoute: AppDemandRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppHeatmapsRoute: AppHeatmapsRoute,
  AppOptimizationRoute: AppOptimizationRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppResourceSharingRoute: AppResourceSharingRoute,
  AppUsersRoute: AppUsersRoute,
  AppUtilizationRoute: AppUtilizationRoute,
  AppWaitlistRoute: AppWaitlistRoute,
  AppDepartmentHeadDashboardRoute: AppDepartmentHeadDashboardRoute,
  AppInstitutionAdminDashboardRoute: AppInstitutionAdminDashboardRoute,
  AppManagerDashboardRoute: AppManagerDashboardRoute,
  AppResearcherDashboardRoute: AppResearcherDashboardRoute,
  AppStudentDashboardRoute: AppStudentDashboardRoute,
  AppSystemAdminDashboardRoute: AppSystemAdminDashboardRoute,
  AppTechnicianDashboardRoute: AppTechnicianDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
