ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;

UPDATE users
SET role = CASE role
    WHEN 'ROLE_USER' THEN 'ROLE_STUDENT'
    WHEN 'ROLE_RESEARCHER' THEN 'ROLE_ASSISTANT_PROFESSOR'
    WHEN 'ROLE_TECHNICIAN' THEN 'ROLE_LAB_ASSISTANT'
    WHEN 'ROLE_MANAGER' THEN 'ROLE_HOD'
    WHEN 'ROLE_DEPARTMENT_HEAD' THEN 'ROLE_HOD'
    WHEN 'ROLE_INSTITUTION_ADMIN' THEN 'ROLE_SYSTEM_ADMIN'
    ELSE role
END
WHERE role IN (
    'ROLE_USER',
    'ROLE_RESEARCHER',
    'ROLE_TECHNICIAN',
    'ROLE_MANAGER',
    'ROLE_DEPARTMENT_HEAD',
    'ROLE_INSTITUTION_ADMIN'
);

ALTER TABLE users ADD CONSTRAINT users_role_check
CHECK (role IN (
    'ROLE_STUDENT',
    'ROLE_LAB_ASSISTANT',
    'ROLE_ASSISTANT_PROFESSOR',
    'ROLE_PROFESSOR',
    'ROLE_HOD',
    'ROLE_SYSTEM_ADMIN'
));

SELECT role, COUNT(*) AS user_count
FROM users
GROUP BY role
ORDER BY role;
